### ISSUE TITLE
nginx-ingress installation instructions reference deprecated repo

### ISSUE THREAD

**Issue by gregeva** [Azure/Industrial-IoT#1012]
**Describe the bug**
The [documentation for deploying the nginx ingress controller](https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-add-aks-to-ps1.md#deploy-ingress-nginx-helm-chart) references a deprecated repository and needs to be updated to its replacement.

**To Repair**
Replace the https://kubernetes.github.io/ingress-nginx address with https://charts.helm.sh/stable

**Screenshots**
![Documentation Error - nginx-ingress Repository Deprecated Needs Changing](https://user-images.githubusercontent.com/7951014/104634446-eb74f980-56a0-11eb-9ec0-754fb3a617b5.png)

**Comment by karok2m** [comment]
@gregeva, please note that https://charts.helm.sh/stable/ states that the repo is deprecated, please see [status of the project](https://github.com/helm/charts/blob/master/README.md#status-of-the-project) and [deprecation timeline](https://github.com/helm/charts/blob/master/README.md#deprecation-timeline) under **Contributing**. And both NGINX Ingress Controller's [Installation Guide Using Helm](https://kubernetes.github.io/ingress-nginx/deploy/#using-helm) page as well as their page on [Artifact Hub](https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx) point to `https://kubernetes.github.io/ingress-nginx`. So that is correct.

The error that you are seeing is for `stable` repo that you have, that is pointing to `https://kubernetes-charts.storage.googleapis.com/`. That one is indeed deprecated. So you would have to remove your old `stable` repo and add a new one that points to `https://charts.helm.sh/stable`.
