### ISSUE TITLE
When running opc-publisher:2.5.4 inside iotedgehubdev-runtime, it does not detect 'RunningInIoTEdgeContext' correctly

### ISSUE THREAD

**Issue by perttvil** [Azure/Industrial-IoT#1211]
I am running docker container mcr.microsoft.com/iotedge/opc-publisher:2.3.3 as a module inside Iot Edge runtime.
Everything works fine with version 2.3.3. 

It does not have any configuration directly to Iot Hub (no connections string) and communication to Iot Hub goes via Iot Edge runtime routes and internal modules.

If I update mcr.microsoft.com/iotedge/opc-publisher:2.3.3 to any newer version, lets say 2.5.4 using the same configuration it wont start at all and says:

`
OPCPublisher                  | [13:24:50 INF] Attempting to read device connection string from cert store using subject name: publisher
OPCPublisher                  | [13:24:50 FTL] Device connection string not found in secure store. Please pass it in at least once via command line option. Can not connect to IoTHub. Exiting...
OPCPublisher                  | [13:24:50 FTL]    at OpcPublisher.IotHubCommunication..ctor() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\IotHubCommunication.cs:line 157
OPCPublisher                  |    at OpcPublisher.IotHubCommunication.get_Instance() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\IotHubCommunication.cs:line 62
OPCPublisher                  |    at OpcPublisher.Program.MainAsync(String[] args) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\Program.cs:line 742
OPCPublisher                  | System.ArgumentException: Device connection string not found in secure store. Please pass it in at least once via command line option. Can not connect to IoTHub. Exiting...
OPCPublisher                  |    at OpcPublisher.IotHubCommunication..ctor() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\IotHubCommunication.cs:line 157
OPCPublisher                  |    at OpcPublisher.IotHubCommunication.get_Instance() in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\IotHubCommunication.cs:line 62
OPCPublisher                  |    at OpcPublisher.Program.MainAsync(String[] args) in D:\a\1\s\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Publisher\src\Program.cs:line 742
OPCPublisher                  | [13:24:50 FTL] Publisher exiting... 
`

So do newer versions really need connection string configuration to Iot Hub and if so, why? 
I read other old github issues, and from those I understood that connection string configuration should not be necessary when working inside Iot Edge runtime. ie: https://github.com/Azure/iot-edge-opc-publisher/issues/155#issuecomment-436478681

So what is the truth?

OpcPubisher module configuration:
`"OPCPublisher": {
                        "settings": {
                            "image": "mcr.microsoft.com/iotedge/opc-publisher:2.5.4",
                            "createOptions": "{\"Hostname\":\"publisher\",\"Cmd\":[\"--pf=/appdata/pn.json\",\"--aa\"],\"HostConfig\":{\"Binds\":[\"/opt/iotedge/opc-ua:/appdata\"],\"ExtraHosts\":[\"mbp-vp.local:192.168.1.107\"]}}"
                        },
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "never",
                        "version": "1.0"
                    }`

Published nodes configuration (pn.json):
`[
  {
    "EndpointUrl": "opc.tcp://mbp-vp.local:53530/OPCUA/SimulationServer",
    "UseSecurity": false,
    "OpcNodes": [
      {
        "Id": "ns=3;i=1001"
      },
      {
        "Id": "ns=3;i=1002"
      }
    ]
  }
]`

**Comment by dacolgit** [comment]
tested with opc publisher version 2.8.2, iotedgehubdev version 0.14.14.

Create and edge device in IoTHub

Setup iotedgehubdev:
`iotedgehubdev setup -c "<edge-device-connection-string>"`
Start and debug a single module
`iotedgehubdev start `
Output module credential
`iotedgehubdev modulecred`
Create an EdgeHubConnectionString env variable with the value returned from previous step

Start publisher module

Publisher starts publishing using iotedgehubdev. 
In the log publisher displays 'Running outside iotedge context.', but this is just because in simulation environment
Edge Hub connection string is passed to module via environment variable vs. IoT edge where the iotedged daemon does it securely.
If iotedgehubdev is stopped the publisher returns the following error:

![image](https://user-images.githubusercontent.com/7942439/161989750-a1a1b57a-295a-4bfd-ae36-4ce9a692e447.png)

doc references:
[Azure/iotedgehubdev: IoT Edge Hub Dev Tool (github.com)](https://github.com/Azure/iotedgehubdev)
[Develop and debug modules for Azure IoT Edge | Microsoft Docs](https://docs.microsoft.com/en-gb/azure/iot-edge/how-to-vs-code-develop-module?view=iotedge-2020-11)
