### ISSUE TITLE
Feature request: Replace published nodes using a single direct method

### ISSUE THREAD

**Issue by fbeltrao** [Azure/Industrial-IoT#1214]
To support a scenario where publisher configuration is stored in an external system it would be great to replace the published nodes using direct methods.
Instead of making multiple add/remove node calls a single direct method call would set all the desired nodes to be published.

More details:
* Monitored items would be published using the module identity.
* Direct method call to replace published nodes supports chunking due to direct method payload limits.
* Appling the new publish nodes is atomic (no partial success).
* Published nodes are stored in disk and survive module restarts.
* Publisher acknowledges the current version applied (related to [this](https://github.com/Azure/iot-edge-opc-publisher/issues/278))
* [Nice to have] We can rollback applied versions by setting a previous version. If the published nodes file is already present we wouldn't have to send nodes again.

**Comment by marcschier** [comment]
This is now technically possible in 2.9.0-preview2.  Technically because of the limitations of method call payload sizes in IoT Hub.  But either using the new HTTP API locally or MQTT or using the chnunking you can call SetConfiguredEndpoints API (counter to GetConfiguredEndpoints which has been around since the beginning) to replace the entire publishednodes.json on the publisher.  You can try this out using the web-api and CLI, documentation will be avialable in the next months.
