### ISSUE TITLE
Skipfirst option in opcpublisher versions above 2.5

### ISSUE THREAD

**Issue by anipuramattom** [Azure/Industrial-IoT#1758]
**Is your feature request related to a problem? Please describe.**
I am working on opcpublisher2.8.1 and it seems that "SkipFirst" option has been removed from versions above 2.5.
I am connecting to Ignition OpcServer and it seems that every time I do a restart of publisher, it duplicates the value in my database, which is not expected in subscription mode.

Please suggest if there any other option by which I can achieve the same functionality.

**Comment by cristipogacean** [comment]
You're right, the SkipFirst option is still missing in 2.8.x. Unfortunately, there is no alternative option to it available.

**Comment by hansgschossmann** [comment]
@anipuramattom  actually the behavior is correct by spec and SkipFirst was a "special" feature added to OPC Publisher < 2.6 to address the side effect you are experiencing.

**Comment by gibin-francis-maersk** [comment]
@hansgschossmann but how we can handle thousands of duplicate messages coming from opc module when ever we restart the module ?

**Comment by hansgschossmann** [comment]
@gibin-francis-maersk there is not really a good work around. The options you have are limited to IoT Edge processing. Routing all OPC Publisher messages to a filter module which tries to detect the connect event might do it. But this can be unreliable since it depends on the quality of the detection logic and adds additional latency, since you need to inspect each event.
Without doubt the right approach is to add back the SkipFirst option.

**Comment by gibin-francis-maersk** [comment]
@hansgschossmann Thanks for the reply, Will Wait for the same if that cane be considered as feature request.

**Comment by marcschier** [comment]
#1924

**Comment by marcschier** [comment]
Implementation is now in main, will be released in 2.9 community preview release next year.
