### ISSUE TITLE
Cannot use REST API for Discovery Module

### ISSUE THREAD

**Issue by flavoie-robert** [Azure/Industrial-IoT#1869]
**Describe the bug**
When attempting to use an API call to use the discovery module of the IIOT edge device, I am unable to connect to the port 9080 of the localhost that is stated in the documentation (https://github.com/Azure/Industrial-IoT/blob/main/docs/api/registry/readme.md)

**To Reproduce**
1. SSH onto the Edge Gateway device, here is what I have deployed on the device:
![image](https://user-images.githubusercontent.com/60756572/196727471-7aedbc0b-9bcc-4a3d-8937-87778bc86bfb.png)
2. From the device itself, I could normally do an API Call:
`curl localhost:9080/registry/v2/applications`
3. Instead, here is what I obtain:
![image](https://user-images.githubusercontent.com/60756572/196730189-49ca08ed-cdc2-40ad-a0ef-528b068f2c82.png)

**Expected behavior**
I was expecting to receive a list of applications, even if I expected it to be empty so far, as I haven't been able to use any other API calls. I expected to the able to use the API and have the port opened with the discovery module running on my device.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04.05 LTS (GNU/Linux 5.10.104-tegra aarch64)

**Additional context**
When I checked if the port 9080 is opened, i can tell this port wasn't opened:
![image](https://user-images.githubusercontent.com/60756572/196730752-c83285c7-e10a-45bc-850f-78f634159687.png)

**Comment by marcschier** [comment]
If you want to use the micro services on the local host you need to deploy the platform using the -type local parameter and then start all micro services .net projects using e.g., Visual Studio 2022.  Each service then has a dedicated port number, like 9080 for registry. 

If you deploy to cloud, use the cloud endpoint url instead of "localhost".  Here you are not talking to a port, but the reverse proxy or app service and you use the host name then, and the path the micro service is mapped to, e.g., <url>/registry/... etc.  The postman tutorial might be a good starting point.
