### ISSUE TITLE
Get timestamp of OPC Publisher host in pubsub telemetry (as opposed to OPC server timestamp)?

### ISSUE THREAD

**Issue by b-enigma-con** [Azure/Industrial-IoT#1912]
Hello all,

We are running OPC Publisher 2.8.3 together with a custom developed IoT Edge module which formats the OPC UA telemetry pubsub JSON to a custom format. The flow is OPC Publisher -> custom developed module -> IoT Hub. We use a polling-like mechanism to gather the data; publishing interval = sampling interval = heartbeat interval.

We use the default telemetry buffering time of the OPC Publisher of 10 seconds. This means that when the heartbeat interval is 5 sec, we would receive 2 messages at a time in our custom developed IoT Edge module.

The issue is that our custom JSON telemetry format (the one going to the IoT Hub) should have a field containing the timestamp of the moment that the data was fetched, based on the datetime of the OPC Publisher host. The reason of this is that the datetime of the connected PLC’s can’t be trusted in this case, they won’t be synced per se. So with the OPC Publisher pub-sub telemetry, we’re not able to use the sourcetimestamp and servertimestamp, because they are both derived  from the PLC’s datetime. We thought that the “Timestamp” field in the pubsub telemetry format would contain the timestamp of when the value was recorded, based on the datetime in the OPC Publisher, but this field also seems to contain a datetime based on the datetime set in the PLC (/OPC server). It boils down to the next question: when messages are buffered in the OPC Publisher, and we want to process them in another upstream IoT Edge module, how would we be able to get the datetime/timestamp of the moment the value was recorded based on the datetime of the OPC Publisher host itself (which we know is always properly synced). We can’t trust the timestamps associated with the PLC’s (/OPC servers) in this case. 

Thank you in advance.

**Comment by cristipogacean** [comment]
Hello @b-enigma-con, 

All the Timestamps that we set inside of the IoTMessage Body (SourceTimestamp, ServerTimestamp, (Publishing)Timestamp), are generated at the OPC UA Server's side to ensure time consistency, so are not matching your requirement. 

In this case I would firstly disable batching (default telemetry buffering time) so that 1 IoT Hub Message contains exactly 1 OPC UA PubSub Telemetry message. Once this is done, you can use the `enqueuedTime` header property of this IoT Message for your use-case. This is using the endge device host clock, so matches your requirement. Furthermore, the `enqueuedTime` is only relevant when the batching mechanism is disabled because then the message is not cached & delayed but generated & sent as soon as data is received from the OPC UA Server.

Please see the example of a complete PubSub Message including the IoT Hum Message headers [here](https://github.com/Azure/Industrial-IoT/blob/main/docs/dev-guides/telemetry-messages-format.md#opc-ua-pubsub-mode-json-encoding)

I hope this helps you moving forward.

**Comment by hansgschossmann** [comment]
@b-enigma-con does this answers your question?

**Comment by b-enigma-con** [comment]
Thank you, it surely does. I was not aware of the existence of those headers (I used https://learn.microsoft.com/en-us/azure/industrial-iot/reference-opc-publisher-telemetry-format as reference).

**Comment by hansgschossmann** [comment]
Please reactivate if you see it does not work as you expect.
