### ISSUE TITLE
Documentation on how to properly handle endpoint ip changes on existing endpoints

### ISSUE THREAD

**Issue by mwiot** [Azure/Industrial-IoT#2029]
Hi, 
We have an installation that has one endpoint being a UA server. 
Because of a change in the customers network we had to change this ip. I could not find a way to do this using the REST api.

What I did that ended up working was to manually go into cosmosdb and update the ip adress in the publisher config and then update the desired properties for the iot device itself.

Iot device twin update:
![image](https://github.com/Azure/Industrial-IoT/assets/82022527/8f9d8c26-bc27-4a99-b677-3b369c728722)

CosmosDB update: 
![image](https://github.com/Azure/Industrial-IoT/assets/82022527/af787b12-5e09-48f1-bf3b-a868858ec74b)

My questions below:
1. What is the proper way to do an ip change on an existing endpoint?
2. Where is the doc that explains the difference between the two iot devices that will be automatically created when adding endpoints? One is called "DataSetWriterV2_uat59c96a0382219f3a0fccb4046260f6a1d60b90e1" and the other one is named "uat59c96a0382219f3a0fccb4046260f6a1d60b90e1". The DataSetWriterV2 seems to focused on the telemetry coming from the publisher module? Please elaborate a bit to make it clear. Especially on the "uat59c96a0382219f3a0fccb4046260f6a1d60b90e1" device that seems to control endpoint connection. 
3. What is the difference between adding this in the cosmosdb publisher config and the iot device? How does it work? I ended up updating both to make it work as you can see from my post. 

Running IIoT 2.8.1

Best regards

**Comment by marcschier** [comment]
Hi @mwiot, unfortunately 2.8 is out of support. We have no more investment here including documenting the old behavior/setup, that is - if it is not already documented in the last 2.8 (2.8.6) release branch. 

Until you are able to update your customers to 2.9 (which removes the cosmos db storage as dependency and all issues that using it entailed - such as this) the only way is to change the cosmos db record directly.  

Nevertheless, the difference you see here in the 2 IoT Hub device identities is, one is for OPC Twin module managed endpoints (found e.g., by OPC Discovery module and onboarded), and the other for the OPC Publisher data set writer instance (which references the former endpoint via the endpoint id that us used when calling the cloud API. The OPC Publisher device id is used to attach the telemetry stream to a device identity and permissions in IoT Hub. 

Unfortunately, the serialization serializes the endpoint twin information including Endpoint Url etc. into the cosmos db document rather than maintaining the reference through the ID, therefore changing both is the right thing to do.
