### ISSUE TITLE
According to @marcschier, the latest version of the Azure Industrial IoT Platform is 2.9.1, corresponding to Issue ID #2053. Please confirm if this information is correct.

### ISSUE THREAD

**Issue by gauravsep1** [Azure/Industrial-IoT#2062]
**According to @marcschier, the latest version of the Azure Industrial IoT Platform is 2.9.1, corresponding to Issue ID #2053. Please confirm if this information is correct.**

**Comment by marcschier** [comment]
Now it is 2.9.2.  But yes, 2.9 version of this project contains OPC Publisher edge module and the OPC Publisher companion web application.  The AKS/micro services cloud platform (last version was 2.8.6) is EOL since July.  The companion web application enables most of the scenarios of the micro services-based version, but is not a drop-in replacement, meaning work has to be done to move from 2.8.6 to 2.9.2.  Whereas the OPC Publisher edge module 2.9.2+ is intended to be a drop-in replacement for 2.8.7+ OPC Publisher standalone version (run without any cloud platform and configured through pn.json).
