### ISSUE TITLE
Are the module deployment scripts current ? 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [Azure/Industrial-IoT#326]
Are the module deployment scripts current ? IE are these the scripts used by \deploy ? 
ie 
https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/deployment-manifest.md#iot-edge-deployment-manifest

**Comment by marcschier** [comment]
These scripts are workable - however, there is now a simpler way to deploy all required modules and that is through the layered deployments that are created on start up of the services.   Whether the layered deployments are applied are related to whether the "iiotedge" tag is set (see documentation).   Because this is far simpler and also provides automatic alignment of modules with services, I would recommend the layered deployment approach instead of the configuration manifest.
