### ISSUE TITLE
Discovery show for Linux GW in 2.7.12 not for Windows 

### ISSUE THREAD

**Issue by pietrobr** [Azure/Industrial-IoT#393]
I've installed the tool v 2.7.12 in discovery I see only the Linux Gateway, I expect to see the Windows as well.
![image](https://user-images.githubusercontent.com/2890569/79985161-7cb89600-84aa-11ea-829c-5ffdbc442270.png)

**Comment by dacolgit** [comment]
Please check in your IotHub if you have two edge devices: linuxgateway-xxx and wingat-xxx

![image](https://user-images.githubusercontent.com/7942439/80127230-540ccb00-8594-11ea-86aa-2fafb4e2795d.png)

**Comment by pietrobr** [comment]
I've rebooted the simulation and GW Windows VM, now the discover works, but after I click on the  GW link for Win VM I don't see any endpoins
![image](https://user-images.githubusercontent.com/2890569/80137836-2cbdfa00-85a4-11ea-8a9e-2d75113d3dda.png)
Twin modules are connected
![image](https://user-images.githubusercontent.com/2890569/80137986-6db60e80-85a4-11ea-887d-ea91bc8b5b98.png)

**Comment by cristipogacean** [comment]
@pietrobr: for windows you need change the scan mask like described here:
https://github.com/Azure/Industrial-IoT/blob/master/docs/tutorials/tut-discover-assets.md

the issue is that the default scan mask is generated for all the network adapters available in discovery container context. for windows only the internal docker network adapter is available therefore the discovery needs to be explicitly instructed to look for servers in the host's network adapter. Linux containers are smarter and have access to host's nw adapters as well.
