### ISSUE TITLE
Allow for aad-register.ps1 invocation from a Service Principal context

### ISSUE THREAD

**Issue by jleger-ptc** [Azure/Industrial-IoT#553]
**Is your feature request related to a problem? Please describe.**
When trying to enable automated azure dependency deployment via the deploy.ps1 script, we realized that `aad-register.ps1` requires an interactive user when calling into the `Connect-AzureAD` cmdlet from the `New-ADApplications` function.

To leverage these scripts in a pipeline, we would like to use a Service Principal with certificate based authentication which appears to be incompatible with the current implementation

**Describe the solution you'd like**
It would be nice if the `aad-register::New-ADApplications()` function could interrogate the `$context` to determine which overload of the [Connect-AzureAD](https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0) cmdlet to invoke.

Hacking and slashing locally, I was able to achieve what I was looking for with something like:
```powershell
if ($context.Account.Type -eq "ServicePrincipal" -And $context.Account.ExtendedProperties.CertificateThumbprint) {
    $creds = Connect-AzureAD `
        -AzureEnvironmentName $context.Environment.Name `
        -TenantId $context.Tenant.Id `
        -ApplicationId $context.Account.Id `
        -CertificateThumbprint $context.Account.ExtendedProperties.CertificateThumbprint
} 
else {
    $creds = Connect-AzureAD `
        -AzureEnvironmentName $context.Environment.Name `
        -TenantId $context.Tenant.Id `
        -AccountId $context.Account.Id `
        -Credential $context.Account.Credential
}
```

**Describe alternatives you've considered**
A potential alternative would be to provide an `aadConfig.json` file to the deploy.ps1 script to avoid calling into aad-register.ps1 all together. However, this goes against the spirit of the current desire of an automated deployment

I would also be up for suggestions for if there is a way to achieve a "minimal" deployment via another deployment mechanism (does the IAI application have feature parity here?)

**Comment by achalupa-ptc** [comment]
This issue is also related to a limitation where the aad-register.ps1 script only works when running on a Windows server.  jaeger adjusted this script to  eliminate the interactive login.  with that version of the script we're stuck on this error when running on a linux server:

Connect-AzureAD: /Users/Andreas/msai-xxxxxx-work/msai-automation-modules/scripts/azure_fiaas/azure_fiaas_aad_register.ps1:181:18
Line |
 181 |          $creds = Connect-AzureAD `
     |                   ~~~~~~~~~~~~~~~~~
     | Certificate based authentication is not supported in netcore
     | version.

Is there a way that we could get the functionality to run w/o  requiring interactive credentials as well be able to run from within a linux pod please?

**Comment by marcschier** [comment]
We have no plans to support providing access to AAD through service principal.
