### ISSUE TITLE
Minimum deployment of the platform has no web apps

### ISSUE THREAD

**Issue by vslepakov** [Azure/Industrial-IoT#680]
**Describe the bug**
Deployed the minimum version of the platform like this: `.\deploy.ps1 -aadConfig aad.json -type minimum`

This is the result:

![image](https://user-images.githubusercontent.com/1545509/90802384-7383ec80-e317-11ea-834c-43fccf25746a.png)

Why are there no web apps (engineering tool, microservices backend) deployed?

**Comment by karok2m** [comment]
@vslepakov, this is by design. As we have several hosting options (App Service and AKS) for backend microservices, `minimum` deployment type is intended for only creating Azure resources that are required for running the microservices on top of them.

Please use deployment type:
- `services`: if you want the deployment to add backend microservices in addition to Azure resources.
- `app`: if you want both backend microservices and Engineering Tool in addition to Azure resources.
