### ISSUE TITLE
opcpublisher version ready to prod?

### ISSUE THREAD

**Issue by omarine** [Azure/Industrial-IoT#681]
Hello,

Is there is stable version of the opcpublisher  pushable  into production ?

or what is at least the version  of the opcpublisher that covers all features of the opcpublisher (2.5.3) not maintained anymore...

Thanks in advance

**Comment by barnstee** [comment]
Our latest production ready version of OPC Publisher is version 2.7.183. We are working hard on bringing the missing features from 2.5.3 into a future version. What features are you missing specifically?

**Comment by omarine** [comment]
One of the features we are lucking are direct methods, are they implemented via twin module?I can't see how can we call them from.portal like we used to? Where is the list of direct methods already implemented?

**Comment by barnstee** [comment]
Adding direct methods back in is one of the highest priority feature we are working on. If you need them now, please stay on version 2.5.3, which was the last version that supported them. They are documented here: https://github.com/Azure/iot-edge-opc-publisher/blob/master/opcpublisher/HubMethodModel.cs
As soon as we have a release plan when we can bring them back, I will let you know.

**Comment by omarine** [comment]
Great... But can I use the rest api in the meantime ?how are the writes are implemented in the opctwin?direct methods or cloud to device (for long running operations?

**Comment by alevincenzi** [comment]
Hello.

Apologies for jumping in but i have a similar question.

Can you please clarify the difference between the opcUaPublisher in this Induastrial-IoT repo and [this old one](https://github.com/Azure/iot-edge-opc-publisher)? Latest release there is 2.4.1 on July 2019.

The point is there there is a well detailed [readme file](https://github.com/Azure/iot-edge-opc-publisher/blob/master/README.md) with the full documentation but i cannot find its counterpart for the latest 2.7 version of the opcuaPublisher here.

**Comment by barnstee** [comment]
Yep, you got it:
Until 2.4.1 we used the old repo here: https://github.com/Azure/iot-edge-opc-publisher
From 2.5.3 we used the new repo (this one)
We're in the process of updating our docs in the new repo with the new command line arguments, stay tuned.

**Comment by omarine** [comment]
Hi ,

So can someone confirms how the read and write methods are implemented in the opctwin module?are they implemented as direct methods?

**Comment by hansgschossmann** [comment]
hi omarine,
OPC Twin can be running as a standalone module and supports a direct methods. They are not documented, since they are used with the OPC Twin microservice typically.
I will need to check if documenting it makes sense and if it is worth the effort.
Here is a list of the supported methods:
- reset_v2 
- getstatus_v2 
- browse_v2 
- browsenext_v2 
- browsepath_v2 
- valueread_v2 
- valuewrite_v2 
- methodmetadata_v2 
- methodcall_v2 
- noderead_v2 
- nodewrite_v2 
- historyread_v2 
- historyreadnext_v2 
- historyupdate_v2 
- getendpointcertificate_v2 
- activateendpoint_v2 
- deactivateendpoint_v2 

The parameters and the return value for the noderead_v2 which i have put together are:

1. string noderead_v2(string endpoint, string request)
Another direct method of the OPC Twin allows to read metadata of an OPC UA node. This call can be used to read the attributes of a node like the data type. The method offer similar functionality as the Read Service described in the OPC UA specifications Attribute Service Set.
 
Parameter
endpoint will be casted into an EndpointApiModel in the module and must follow the structure described here.
request will be casted into an ReadRequestApiModel described here.
Result
string of type ReadResultModel described here in the payload object with a preceding method status field.
 
The next call does read attributes of the node with the NodeId “ns=2;s=StepUp” from the same endpoint as used for the browse_v2 call above:
Request:
{
    "endpoint": {
        "url": "opc.tcp://opcplc:50000"
    },
    "request": {
        "attributes": [
            {
                "nodeId": "ns=2;s=StepUp",
                "attribute": "DataType"
            }
        ],
        "header": {
            "elevation": {
                "type": "UserName",
                "value": {
                    "user": "user1",
                    "password": "password"
                }
            }
        }
    }
}
 
Response:
{
    "status": 200,
    "payload": {
        "results": [
            {
                "value": "UInt32"
            }
        ]
    }
}

If you look into other calls, let me know and i can try to put together a similar description.

The direct methods are generated at runtime based on class attributes. This is done by the ModuleHost framework.

The simplest way to check it yourself is to look into the file <reporoot>\modules\src\Microsoft.Azure.IIoT.Modules.OpcUa.Twin\src\Controllers\EndpointMethodsController.cs
You will see a class EndpointMethodsController which is tagged with Version attributes. Those generate _v1/_v2 direct methods of the class methods by removing the trailing Async from the method and lowercase them and prepending the version. (e.g. NodeReadAsync is exposed as direct method noderead_v2.
Now you see what can be passed in as request. Additionally you need to pass in an EndpointApiModel to all of those mthods in the EndpointController.

Hope that answers your question. Pls reopen if you need more clarifications.

**Comment by omarine** [comment]
Thanks ,

concernng the features missing,i was looking for a way to athenticate the opcpublisher to a server using X509IdentityToken

but based on the 2.7.183 version i think the User would either be of Type UserNamePassword or null 

![image](https://user-images.githubusercontent.com/13197345/95354445-bb110880-08c4-11eb-9c7c-b68b8c6f93cf.png)

and in the process of the session création : 

![image](https://user-images.githubusercontent.com/13197345/95354601-e4319900-08c4-11eb-8f47-9d2dd2fb82a7.png)


![image](https://user-images.githubusercontent.com/13197345/95354668-f90e2c80-08c4-11eb-9cc7-41be963585a5.png)

does that mean we can't create a session against a server using x509 certificate?

Thanks in advance for the answer.

**Comment by barnstee** [comment]
Yes, only username/password auth is implemented for user auth right now. We will add this to our backlog.
