### ISSUE TITLE
What version of OPC Publisher should I use?

### ISSUE THREAD

**Issue by Jan-Olof** [Azure/Industrial-IoT#827]
I want to use OPC Publisher in IoT Edge as a stand alone module. I am confused as to what version or even repository I should use? (https://github.com/Azure/iot-edge-opc-publisher or https://github.com/Azure/Industrial-IoT.)

Can you help me?

**Comment by barnstee** [comment]
You should always use the Link provided in the Azure Marketplace, it points to the latest and greatest version:
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft_iot.iotedge-opc-publisher?tab=Overview

You shouldn't use the GitHub repos at all, since we build and test the source code ourselves and provide Docker containers through the Microsoft Container Registry.

**Comment by Jan-Olof** [comment]
Thanks a lot for your quick answer! Much appreciated!
